### ISSUE TITLE
DefaultValue on Hidden sets defaultvalue="$value"

### ISSUE THREAD

**Issue by axyr** [adamwathan/form#102]
Should 

``` php
public function defaultValue($value)
    {
        if (! $this->hasValue()) {
            $this->setValue($value);
        }

        return $this;
    }
```

Not be set on Input instead of Text?

**Comment by nCrazed** [comment]
What's the use case for this?

Input is extended by `Checkbox`, `File`, `Hidden`, and `Text`.

* `File` can't have a sensible default value.
* `Checkbox` defines it's own methods for this to fit its inherently different (from most input types) behavior.
* `Hidden` should not be modified by the client and should have its value set explicitly without needing a fallback
