### ISSUE TITLE
How can i set the ID for Hidden Input?

### ISSUE THREAD

**Issue by ricardovigatti** [adamwathan/form#105]
I'm trying to set the ID for my hidden input. Something like:

``` {{ Form::hidden('name', 'value')->id('id') }} ```

I've searched here and at BootForm package and didn't find a solution.

Thanks.

**Comment by JesseLeite** [comment]
@ricardovigatti, sorry for the delay.  You can indeed set the ID, just as you are in the above example.
```php
{!! Form::hidden('name', 'value')->id('id') !!}
```
Outputs:
```html
<input type="hidden" name="name" id="wat">
```
This works in both form and bootforms packages (bootforms actually delegates this to the base form builder) using PHP's magic methods.  Any method not defined by form/bootforms will delegate to `attribute()`.  Example...
```php
{!! Form::hidden('name', 'value')->attribute('lol', 'catz') !!}
{!! Form::hidden('name', 'value')->lol('catz') !!}
```
Both of the above examples will output:
```html
<input type="hidden" name="name" lol="catz">
```

**Comment by ricardovigatti** [comment]
I'm getting a **FatalErrorException: Call to a member function id() on a non-object**.

And i'm trying to use exactly like said above.

```
{!! Form::hidden('name', 'value')->id('someid') !!}

// with attribute the error is the same
{!! Form::hidden('name', 'value')->attribute('id', 'someid') !!}
```

**Comment by JesseLeite** [comment]
@ricardovigatti weird.  Can you confirm which package version you have installed?  If you are on mac or linux, you should be able to run this to find out which version is currently installed:
```bash
cat composer.lock | grep '"name": "adamwathan/form"' -C 1
```

**Comment by ricardovigatti** [comment]
i'm on Windows, anyway, i'm using the last version, tagged as v0.8.10.

I decided to try again and see whats happens:

```php
// did not work
{!! Form::hidden('name', 'value')->attribute('id', 'someid') !!}

// surprise! that works. 
{!! BootForm::hidden('name', 'value')->attribute('id', 'someid') !!}
```

**Comment by JesseLeite** [comment]
@ricardovigatti Curious what `Form` facade/alias is set to in your /config/app.php?

**Comment by ricardovigatti** [comment]
@JesseLeite Awesome! You found the problem.

I remembered of changing my facades to use the Form Collective package.

```php
'AdamForm'  => 'AdamWathan\Form\Facades\Form',
 'BootForm'  => 'AdamWathan\BootForms\Facades\BootForm',
// [ ... ]
'Form'      => 'Collective\Html\FormFacade',
'Html'      => 'Collective\Html\HtmlFacade',
```

Now i'm using ```AdamForm::hidden()``` in my views.

Thanks.

**Comment by JesseLeite** [comment]
@ricardovigatti No problem.  Don't mix your drugs!  And definitely don't mix your form packages!  Adam's base form package is (IMO) a huge improvement to the collective form package.  Unless you are using that collective form package, you could just rip it out ;)
