### ISSUE TITLE
License Information

### ISSUE THREAD

**Issue by SlyDave** [adamwathan/form#107]
Hi @adamwathan ,

I'm looking to use your rather excellent form and bootform code, but I have various licencing restrictions, and I am unable to find anything about how you've licenced your code. Could you add the information to your readme.md ?

Thanks!

**Comment by adamwathan** [comment]
Hey @SlyDave! It's all MIT, but it's only mentioned the Composer configuration:

https://github.com/adamwathan/form/blob/master/composer.json#L10

I just added `LICENSE` files to both repos though, thanks for pointing it out!
