### ISSUE TITLE
Escaping of label contents

### ISSUE THREAD

**Issue by anaisabel19886** [adamwathan/form#121]
Hi, i've just composer updated a project with "adamwathan/bootforms": "^0.8.2" and  "propaganistas/laravel-translatable-bootforms": "~1.3" (on composer.json) and now the labels for the translatable inputs aren't being escaped.

I have opened an issue with propagandistas but they informed me I should open an issue with you, since the escaping of the labels was done bu the form package. (see more here: https://github.com/Propaganistas/Laravel-Translatable-Bootforms/issues/24 ).

Will there be a fix, or I need to revert the update?
Thank you for this package!

**Comment by adamwathan** [comment]
Reverted that change and tagged v0.9.0, thanks.

https://github.com/adamwathan/form/commit/d44534bf812512daa9d5a3b68d0ef7928def99b8

**Comment by anaisabel19886** [comment]
Great, thanks!
