### ISSUE TITLE
How can I replace template for submit button

### ISSUE THREAD

**Issue by cve** [adamwathan/form#25]
Hi,

how can I replace the template or simply replace the class for the submit button. This library uses 'btn-default' as class for submit button, but I want to for example use 'btn-primary' instead of 'btn-default'. I know I can use $element->removeClass('btn-default')->addClass('btn-primary') but this looks ugly for me... Is there any solution how to do that in another way?

**Comment by adamwathan** [comment]
I think this issue belongs on the BootForms repo, but you can do what you want like so:

```
$builder->submit('Submit', 'btn-primary');
```
