### ISSUE TITLE
setOldInputProvider for Check and Radio Inputs

### ISSUE THREAD

**Issue by jonasemde** [adamwathan/form#26]
Did the setOldInputProvider method not prefill values on radio and checkbox inputs?

**Comment by adamwathan** [comment]
Hmm it should, can you post an example? These tests are all passing: https://github.com/adamwathan/form/blob/master/tests/FormBuilderTest.php#L150-L187

**Comment by jonasemde** [comment]
I have posted a message related to that topic here:
https://github.com/adamwathan/form/pull/27
