### ISSUE TITLE
Better testing coverage for Element and FormControl methods

### ISSUE THREAD

**Issue by nCrazed** [adamwathan/form#40]
As discussed in #39, some of the functionality that is not specific to one of the 4 base element types is currently being tested only in the context of `Text` (The base class for all of the `<input>` type implementations).

The other 3 element types (`TextArea`, `Select`, and `Button`) lack the tests.

**Comment by nCrazed** [comment]
@adamwathan what do you think about doing something like this: http://stackoverflow.com/a/7811936/3784306

**Comment by nCrazed** [comment]
@adamwathan have you had the chance to consider the above approach?

I've got some free time coming up soon and wouldn't mind working on a PR.

**Comment by adamwathan** [comment]
Yeah I think that would be fine :+1:

**Comment by nCrazed** [comment]
Your latest video seems relevant :D

**Comment by nCrazed** [comment]
I started working on this with traits, but now I am not sure if it's worth bumping supported PHP version just for sake of better testing coverage when there are alternative ways to achieve the coverage improvements.

What are your thoughts on this?

**Comment by adamwathan** [comment]
I'm fine with traits and bumping the PHP dependency to 5.4 :+1:

**Comment by nCrazed** [comment]
Can you think any reasons why we can't add newer versions of PHPto travis test targets?

Specifically `5.6`, `7.0` and `hhvm`

**Comment by adamwathan** [comment]
Nope, we should do that! I think 5.4, 5.5, 5.6 and 7.0 is good, not too concerned about HHVM.
