### ISSUE TITLE
Can`t set defaultCheckedState for null or 0 values

### ISSUE THREAD

**Issue by rorc** [adamwathan/form#44]
$builder->checkbox('bar_kitchen[]', 0 or null)->defaultCheckedState(false) => checked

**Comment by nCrazed** [comment]
@rorc what version of the package are you using?

The following test code pass against the current HEAD (8b33f05fc0a11abd8c08e3b1e8fd04d9c41ddea8):

```php
$checkbox = new Checkbox('bar_kitchen[]', 0);
$expected ='<input type="checkbox" name="bar_kitchen[]" value="0">';
$result = $checkbox->defaultCheckedState(false)->render();

$this->assertEquals($expected, $result);

$checkbox = new Checkbox('bar_kitchen[]', 0);
$expected ='<input type="checkbox" name="bar_kitchen[]" value="0" checked="checked">';
$result = $checkbox->defaultCheckedState(true)->render();

$this->assertEquals($expected, $result);
```

As for the `null`, HTML has no concept of null and `value` attribute is mandatory for `<input type="checkbox">`; how do you expect `checkbox('name', null)` to be rendered?
