### ISSUE TITLE
Feature/ Enhancement: Need a PATCH method

### ISSUE THREAD

**Issue by bmullican** [adamwathan/form#52]
https://github.com/adamwathan/form/blob/master/src/AdamWathan/Form/Elements/FormOpen.php

FormOpen.php needs a "PATCH" method for those who may wish to use it.

public function patch()
{
    return $this->setHiddenMethod('PATCH');
}

**Comment by adamwathan** [comment]
Will gladly accept a PR :)

**Comment by bmullican** [comment]
Sent. Thanks.
