### ISSUE TITLE
Submit Input instead of Button?

### ISSUE THREAD

**Issue by iolson** [adamwathan/form#56]
When doing

```php
{!! $builder->submit('Search') !!}
```

Is there a nice way of outputing that as `<input type="submit" value="Search">` instead of the button?

**Comment by adamwathan** [comment]
Hey Ian! No, the package won't generate an `<input type="submit">` tag. If you really need it, I would just write the markup, you don't lose any functionality by not generating it through the package.

I would recommend using a `button` if you can, for the same reasons mentioned in the Bootstrap docs:

http://getbootstrap.com/css/#callout-buttons-ff-height
