### ISSUE TITLE
Remember old input?

### ISSUE THREAD

**Issue by canfiax** [adamwathan/form#58]
How does the "remember old input" works? It isn't pretty clear as per the documentation.

I am using BootForm, but I guess this is the same.

                {!! BootForm::open(['files' => true])->put()->action(route('category.update', $category->id))->multipart() !!}
                    {!! BootForm::text('Name', 'name')->value($category->name) !!}
                    {!! BootForm::text('Slug', 'slug')->value($category->slug) !!}
                    {!! BootForm::submit('Save') !!}
                {!! BootForm::close() !!}

If errors happens under Request validation, the old input is now populated.

**Comment by adamwathan** [comment]
It should work out of the box with Laravel if you are using the service provider. The form builder just needs to be instantiated with an implementation of [this interface](https://github.com/adamwathan/form/blob/master/src/AdamWathan/Form/OldInput/OldInputInterface.php) that returns the old input when it's asked for.

There is a bundled Laravel implementation that relies on the session here: https://github.com/adamwathan/form/blob/master/src/AdamWathan/Form/OldInput/IlluminateOldInputProvider.php

In your controllers when validation fails, make sure you are including the `withOldInput()` call in your redirects, something like:

```
return redirect()->back()->withErrors($validation)->withOldInput();
```

**Comment by canfiax** [comment]
I dont validate in the controller but in a request (the method Rules). I guess that is why it does not function.

**Comment by adamwathan** [comment]
It should still work, here's how it constructs the response when using custom requests:

https://github.com/laravel/framework/blob/8fabb94f76dbdd917c58ebfa3bcf859f714a8ad4/src/Illuminate/Foundation/Validation/ValidatesRequests.php#L87-L89

Is there anything in the exception handling process you've customized?

**Comment by canfiax** [comment]
Strange. I am using the service provider. Should I open the form in a specific way? This is how I open:

		{!! BootForm::openHorizontal(['lg' => [3, 9]])->addClass('row')->put()->action(URL::route('user.profile', $user->slug)) !!}
			<input type="hidden" name="_token" value="{{ csrf_token() }}">

			{!! BootForm::text('First name', 'firstname')->value($user->firstname) !!}
			{!! BootForm::text('Last name', 'lastname')->value($user->lastname) !!}
			{!! BootForm::email('E-mail', 'email')->value($user->email) !!}
		{!! BootForm::close() !!}

I am using a UpdateUserRequest, that looks like this: http://laravel.io/bin/mGDqE
It extends the basic Request that looks like this: http://laravel.io/bin/GyXxk

Can't figure out what I am missing.

I have installed BugSnag on my application, which changes app/Exceptions/Handler.php to extend `Bugsnag\BugsnagLaravel\BugsnagExceptionHandler` instead of the default `Illuminate\Foundation\Exceptions\Handler`. However, the BugsnagExceptionHandler extends `Illuminate\Foundation\Exceptions\Handler`, so I guess it shouldn't be a problem. See https://github.com/bugsnag/bugsnag-laravel#how-to-install.

**Comment by adamwathan** [comment]
Any chance you can reproduce in a small sample Laravel app that you can post publicly? Happy to pull it down and test.

**Comment by canfiax** [comment]
Hey @adamwathan sorry for not getting back. The thought of having to throw a sample app seems complicated, so  I got away from it.

I can tell that it still is an issue on our codebase. It does not remember input.

However, I have just noticed that for some reason, it does remember the selection of `<select>` don't know if it can help the debugging.

**Comment by canfiax** [comment]
@adamwathan issue still persists even after #63.

I have figured out that it will remember the old input if my input is created like this:

    {!! BootForm::text('Name', 'name') !!}

As soon as I provide a "value" it will not remember old input:

    {!! BootForm::text('Name', 'name')->value($page->name) !!}

Is there a specific way you need to provide the value when wanting to remember old input? It is for an "edit" form.

**Comment by adamwathan** [comment]
The `value` call will override any old input; it has the highest precedence. This is probably what you want:

`{!! BootForm::text('Name', 'name')->defaultValue($page->name) !!}`

**Comment by canfiax** [comment]
Thanks, would be great to have that noted somewhere :)

**Comment by adamwathan** [comment]
It is in the docs :) https://github.com/adamwathan/form#remembering-old-input

![image](https://cloud.githubusercontent.com/assets/4323180/13056066/e7ec8514-d3e0-11e5-955f-6f6250bd34aa.png)

**Comment by canfiax** [comment]
I see, thanks! :)
