### ISSUE TITLE
Selected for multiple select

### ISSUE THREAD

**Issue by rorc** [adamwathan/form#60]
Please replace isSelected method on Select class:

```
    protected function isSelected($value)
    {
        if (isset($this->selected)) {
            return $this->selected == $value || is_array($this->selected) && in_array($value, $this->selected);
        }

        return false;
    }
```

**Comment by adamwathan** [comment]
What issue is this actually solving? Can you submit a failing test case?

**Comment by rorc** [comment]
I want select exists multiple options like this:
```
$builder->select('name[]', $array)->select($arrayOfSelectedValues);
```
Now, your method isSelected is not support this feature for multiple select.

**Comment by adamwathan** [comment]
It should support multiple select, as per the tests: 

https://github.com/adamwathan/form/blob/master/tests/SelectTest.php#L150-L175

Will investigate your specific use case and see if there are any issues.

**Comment by rorc** [comment]
I talk not about defaultValue...

**Comment by rorc** [comment]
Just try to select multiple values on some multiple select (selectName[]). Values will not be selected.

**Comment by adamwathan** [comment]
Just added this test which passes: https://github.com/adamwathan/form/commit/ca96009e9c24795046d81dd9fb907f9dee8a6a36

**Comment by adamwathan** [comment]
It works without the `multiple()` call as well.
