### ISSUE TITLE
FormBuilder::bind() support for multiple models in one form.

### ISSUE THREAD

**Issue by Dmitri-Sintsov** [adamwathan/form#66]
How can I do

    <?= $builder->open(); ?>
    foreach($models as $model) {
        <?= $builder->bind($model); ?>
        <?= $builder->text('first_name'); ?>
        <?= $builder->text('last_name'); ?>
        <?= $builder->email('email'); ?>
        <?= $builder->date('date_of_birth'); ?>
    }
    <?= $builder->close(); ?>

Preferrably "first_name[$model->id]" suffix should automatically be used, but manual override via ::bind() argument is nice to have for additional flexibility.

Is that already possible?

**Comment by adamwathan** [comment]
Currently not possible, but interesting idea. I don't think I'll likely get around to playing with this idea myself any time soon, but I would happily look at any pull requests that work towards implementing it to see if it's worth adding to the project.

Thanks!
