### ISSUE TITLE
Form::bind() and relationships

### ISSUE THREAD

**Issue by Erwane** [adamwathan/form#69]
Consider having one model Devis and one DevisData. 
One Devis hasMany DevisData, linked by DevisData.devis_id field.

how can i do that in controller and view ? :
Controller : 
$devis = Devis::find($id);
$datas = $devis->datas; // hasMany defined in model

View :
Form::bind($devis + $datas)

Inputs are automatically filled.

My input field names looks like that : 
<input type="text" name="row[0][description]" value="">
<input type="text" name="row[1][description]" value="">
<input type="text" name="row[2][description]" value="">

I think we should define the "row" in Form::bind() method.

**Comment by adamwathan** [comment]
Currently not supported automatically, would have to bind the values yourself. Happy to look at PRs, likely won't get around to implementing it myself though.
