### ISSUE TITLE
Add posibility for selectYear

### ISSUE THREAD

**Issue by simplenotezy** [adamwathan/form#73]
I does not seem as though selectYear is supported, like so:

```
{{ Form::selectYear('year', 2013, 2015) }}
```

Described here: http://laravel-recipes.com/recipes/165/creating-a-select-year-field

**Comment by adamwathan** [comment]
Happy to accept a PR :+1:

**Comment by nCrazed** [comment]
The can be easily achieved using the PHP's [range](http://php.net/manual/en/function.range.php) functions:

```php
Form::select('year', range(2013, 2015));
```

Is it really worth sub-classing the Select element and introducing additional tests for it just to overload its constructor to call the range function for you?

**Comment by adamwathan** [comment]
@nCrazed is totally right, just use `range` 😊
