### ISSUE TITLE
available xss attack

### ISSUE THREAD

**Issue by amoseev** [adamwathan/form#95]
Hi! 
There isn't escaping for html attributes. 
I faced with problem with select element and option=`><script>alert('fgdfgdfg')</script>`. This option bring alert.
Another example: value for "text" contain `test "oo"`. It show only test.
In similar library attributes escaped by default:
https://github.com/LaravelCollective/html/blob/5.2/src/HtmlBuilder.php#L421

Thanks!

**Comment by iainheng** [comment]
Any update on this issue? This seems to be a serious shortcoming of the library

**Comment by adamwathan** [comment]
Sorry I am a bad maintainer 👀 I haven't used this library myself in a few years. Will happily look at any PRs to fix this.

**Comment by JesseLeite** [comment]
Going to close this.  If any other XSS vulnerabilities are found, feel free to submit new issue/PR 👍
